name: Terraform

on:
  push:
    paths:
      - 'WebApp/**'
    branches:
      - main
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebApp  # ✅ Set your Terraform config path here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        id: format
        run: terraform fmt -check
        continue-on-error: true

      - name: Validate Terraform files
        run: terraform validate

      - name: Apply Terraform
        run: terraform apply -auto-approve

        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_sql_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
          
      #- name: Azure Login
       # uses: azure/login@v2
       # with:
        #  client-id: ${{ secrets.AZURE_CLIENT_ID }}
         # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         #client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
